---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watcher-role
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - events
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watcher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watcher-role
subjects:
  - kind: ServiceAccount
    name: watcher

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-watcher-config
immutable: true
data:
  config.yaml: |
    modules:
      - watcher: pods
        exclude_pods: []
      - watcher: events
        exclude_pods: []
    notify_url: 'https://example.com/post_notify

---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-watcher
spec:
  containers:
  - name: k8s-watcher
    image: ghcr.io/finkandreas/k8s-watcher:latest
    imagePullPolicy: Always
    command: ['python', '/opt/watcher.py', '--config=/etc/k8s-watcher/config.yaml']
    volumeMounts:
      - name: config
        mountPath: /etc/k8s-watcher
  serviceAccountName: watcher
  volumes:
    - name: config
      configMap:
        name: k8s-watcher-config
